#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once"
    ROOT_DEV=$(findmnt / -o source -n)
    ROOT_FS=$(findmnt / -o fstype -n)
    if [ "$ROOT_FS" = "ext4" ]; then
      echo "resize2fs -F -f $ROOT_DEV"
      touch /.resized
      update-rc.d resize2fs_once remove
      rm /etc/init.d/resize2fs_once
    elif [ "$ROOT_FS" = "f2fs" ]; then
      echo "resize.f2fs $ROOT_DEV"
      touch /.resized
      update-rc.d resize2fs_once remove
      rm /etc/init.d/resize2fs_once
    else
      log_daemon_msg "WARNING! Unknown filesystem, skipping filesystem resize."
      update-rc.d resize2fs_once remove
      rm /etc/init.d/resize2fs_once
      exit
    fi
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac